stages:
  - build
  - test
  - deploy

image: node:9

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dest/
    expire_in: 1 day

test:src:
  stage: test
  script:
    - npm install
    - npm run test-src

test:dest:
  stage: test
  script:
    - npm install
    - npm run test-dest
  dependencies:
    - build
