stages:
  - build
  - test
  - deploy

image: node:9

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

test:src:
  stage: test
  script:
    - npm install
    - npm run test-src
  dependencies: []

test:dist:
  stage: test
  script:
    - npm install
    - npm run test-dist
  dependencies:
    - build
