stages:
  - pre
  - build
  - test
  - deploy

image: node:9

pre:lint:
  stage: pre
  script:
    - npm install
    - npm run lint
  dependencies: []

pre:src:
  stage: pre
  script:
    - npm install
    - npm run test-src
  dependencies: []

build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm run bundle
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

test:coverage:
  stage: test
  script:
    - npm install
    - npm run coverage
  dependencies:
    - build
