stages:
  - build
  - test
  - deploy

image: node:9

build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm run bundle
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test-src
    - npm run coverage
  dependencies:
    - build
