stages:
  - build
  - deploy

image: node:9

build:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run test-src
    - npm run build
    - npm run coverage
    - npm run bundle
    - npm run doc
  artifacts:
    paths:
      - dist/
      - doc/
    expire_in: 1 day
